baseurl = "/"
languageCode = "en-us"
title = "Patrick's Data Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
# baseurl = 



#[permalinks]
#    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Research"
    url = "/research/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/patrickmlong"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/patrickmarklong/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

